description: Takes the input URL and extracts the required information to generate
  the Discord embed card message for the Discord repository.
input-class: RetrieveEmbedInfoInput
name: RetrieveEmbedInfo
output-class: RetrieveEmbedInfoOutput
parameters:
  timeout: 10
